apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-frontend
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.type }}
  selector:
    app: frontend
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.frontend.ports | toYaml | nindent 2 -}}