apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: app-issuer
  namespace: nazim
spec:
  acme:
       # The ACME server URL
       server: https://acme-v02.api.letsencrypt.org/directory
       # Email address used for ACME registration
       email: nazim.mukhtarbekov26@gmail.com
       # Name of a secret used to store the ACME account private key
       privateKeySecretRef:
         name: app-cert
       # Enable the HTTP-01 challenge provider
       solvers:
       - http01:
           ingress:
             class:  nginx
         selector: {}

# Dev Nz